import Foundation

let HOME = FileManager.default.homeDirectoryForCurrentUser.path

let allCategories: [Category] = [

    // ── Xcode ──────────────────────────────────────────────────────────────
    .init(name: "Xcode", icon: "🔨", targets: [
        .init(label: "DerivedData",
              path: "\(HOME)/Library/Developer/Xcode/DerivedData",
              hint: "Build artifacts — Xcode recreates automatically",
              cleanup: "rm -rf ~/Library/Developer/Xcode/DerivedData",
              safety: .safe,
              subAnalyzer: XcodeDerivedDataAnalyzer()),
        .init(label: "iOS DeviceSupport",
              path: "\(HOME)/Library/Developer/Xcode/iOS DeviceSupport",
              hint: "Debug symbols for physical devices, grouped by iOS version",
              cleanup: nil,
              safety: .soft,
              subAnalyzer: XcodeDeviceSupportAnalyzer()),
        .init(label: "watchOS DeviceSupport",
              path: "\(HOME)/Library/Developer/Xcode/watchOS DeviceSupport",
              hint: "Debug symbols for watchOS devices",
              cleanup: nil,
              safety: .soft,
              subAnalyzer: XcodeDeviceSupportAnalyzer()),
        .init(label: "visionOS DeviceSupport",
              path: "\(HOME)/Library/Developer/Xcode/visionOS DeviceSupport",
              hint: "Debug symbols for visionOS devices",
              cleanup: nil,
              safety: .soft,
              subAnalyzer: XcodeDeviceSupportAnalyzer()),
        .init(label: "Archives",
              path: "\(HOME)/Library/Developer/Xcode/Archives",
              hint: "App Store / TestFlight archives",
              cleanup: nil,
              safety: .manual),
        .init(label: "CoreSimulator",
              path: "\(HOME)/Library/Developer/CoreSimulator/Devices",
              hint: "iOS/watchOS/tvOS/visionOS simulator images",
              cleanup: "xcrun simctl delete unavailable",
              safety: .soft,
              subAnalyzer: XcodeSimulatorAnalyzer()),
        .init(label: "Xcode Caches",
              path: "\(HOME)/Library/Caches/com.apple.dt.Xcode",
              hint: "Xcode cache",
              cleanup: "rm -rf ~/Library/Caches/com.apple.dt.Xcode",
              safety: .safe),
    ]),

    // ── Node.js ────────────────────────────────────────────────────────────
    .init(name: "Node.js", icon: "🟩", targets: [
        .init(label: "npm cache",
              path: "\(HOME)/.npm",
              hint: "npm package cache — safe to delete",
              cleanup: "npm cache clean --force",
              safety: .safe),
        .init(label: "yarn cache",
              path: "\(HOME)/.yarn/cache",
              hint: "yarn package cache",
              cleanup: "yarn cache clean",
              safety: .safe),
        .init(label: "pnpm store",
              path: "\(HOME)/.pnpm-store",
              hint: "pnpm content-addressable store",
              cleanup: "pnpm store prune",
              safety: .safe),
        .init(label: "nvm node versions",
              path: "\(HOME)/.nvm/versions/node",
              hint: "All Node versions installed via nvm",
              cleanup: "nvm ls",
              safety: .manual,
              subAnalyzer: NVMNodeAnalyzer()),
        .init(label: "Volta node toolchain",
              path: "\(HOME)/.volta/tools/image/node",
              hint: "Node versions managed by Volta",
              cleanup: "volta list",
              safety: .manual),
    ]),

    // ── Rust ───────────────────────────────────────────────────────────────
    .init(name: "Rust", icon: "🦀", targets: [
        .init(label: "cargo registry",
              path: "\(HOME)/.cargo/registry",
              hint: "Crate sources and metadata",
              cleanup: "cargo cache --autoclean",
              safety: .soft),
        .init(label: "cargo git deps",
              path: "\(HOME)/.cargo/git",
              hint: "Git-sourced Cargo dependencies",
              cleanup: "cargo cache --autoclean",
              safety: .soft),
        .init(label: "rustup toolchains",
              path: "\(HOME)/.rustup/toolchains",
              hint: "Installed Rust toolchains (stable/nightly/etc.)",
              cleanup: "rustup toolchain list",
              safety: .manual,
              subAnalyzer: RustupToolchainsAnalyzer()),
        .init(label: "rustup downloads",
              path: "\(HOME)/.rustup/downloads",
              hint: "Cached rustup component downloads",
              cleanup: "rustup self clean",
              safety: .safe),
    ]),

    // ── Java / Kotlin ──────────────────────────────────────────────────────
    .init(name: "Java / Kotlin", icon: "☕", targets: [
        .init(label: "Gradle caches",
              path: "\(HOME)/.gradle/caches",
              hint: "Dependencies for all Gradle projects",
              cleanup: "rm -rf ~/.gradle/caches",
              safety: .soft),
        .init(label: "Gradle wrappers",
              path: "\(HOME)/.gradle/wrapper/dists",
              hint: "Gradle distributions (each project downloads its own version)",
              cleanup: nil,
              safety: .soft,
              subAnalyzer: GradleWrapperAnalyzer()),
        .init(label: "Maven (.m2)",
              path: "\(HOME)/.m2/repository",
              hint: "Local Maven repository",
              cleanup: nil,
              safety: .soft),
        .init(label: "IntelliJ caches",
              path: "\(HOME)/Library/Caches/JetBrains",
              hint: "JetBrains IDE caches (IDEA, Android Studio, etc.)",
              cleanup: nil,
              safety: .safe),
    ]),

    // ── Android ────────────────────────────────────────────────────────────
    .init(name: "Android", icon: "🤖", targets: [
        .init(label: "Android SDK",
              path: "\(HOME)/Library/Android/sdk",
              hint: "Platform tools, NDK, build tools, emulators",
              cleanup: nil,
              safety: .manual,
              subAnalyzer: AndroidSDKAnalyzer()),
        .init(label: "Android Emulator data",
              path: "\(HOME)/.android/avd",
              hint: "Android emulator disk images",
              cleanup: nil,
              safety: .manual,
              subAnalyzer: AndroidAVDAnalyzer()),
    ]),

    // ── Python ─────────────────────────────────────────────────────────────
    .init(name: "Python", icon: "🐍", targets: [
        .init(label: "pyenv versions",
              path: "\(HOME)/.pyenv/versions",
              hint: "Python versions installed via pyenv",
              cleanup: "pyenv versions",
              safety: .manual,
              subAnalyzer: PyenvVersionsAnalyzer()),
        .init(label: "pip cache (Library)",
              path: "\(HOME)/Library/Caches/pip",
              hint: "pip package cache",
              cleanup: "pip cache purge",
              safety: .safe),
        .init(label: "pip cache (hidden)",
              path: "\(HOME)/.cache/pip",
              hint: "pip package cache (alternate location)",
              cleanup: "pip cache purge",
              safety: .safe),
        .init(label: "virtualenvs",
              path: "\(HOME)/.virtualenvs",
              hint: "Python virtual environments (virtualenvwrapper)",
              cleanup: nil,
              safety: .manual),
        .init(label: "uv cache",
              path: "\(HOME)/.cache/uv",
              hint: "uv package cache (modern pip alternative)",
              cleanup: "uv cache clean",
              safety: .safe),
    ]),

    // ── Ruby ───────────────────────────────────────────────────────────────
    .init(name: "Ruby", icon: "💎", targets: [
        .init(label: "rbenv versions",
              path: "\(HOME)/.rbenv/versions",
              hint: "Ruby versions installed via rbenv",
              cleanup: "rbenv versions",
              safety: .manual,
              subAnalyzer: RbenvVersionsAnalyzer()),
        .init(label: "gem home",
              path: "\(HOME)/.gem",
              hint: "Installed Ruby gems",
              cleanup: nil,
              safety: .manual),
        .init(label: "CocoaPods cache",
              path: "\(HOME)/Library/Caches/CocoaPods",
              hint: "CocoaPods pod cache",
              cleanup: "pod cache clean --all",
              safety: .safe),
        .init(label: "CocoaPods specs",
              path: "\(HOME)/.cocoapods",
              hint: "Local CocoaPods specs repository",
              cleanup: "pod repo remove master",
              safety: .soft),
    ]),

    // ── Flutter / Dart ─────────────────────────────────────────────────────
    .init(name: "Flutter / Dart", icon: "💙", targets: [
        .init(label: "pub-cache",
              path: "\(HOME)/.pub-cache",
              hint: "Dart pub package cache",
              cleanup: "dart pub cache clean",
              safety: .soft),
        .init(label: "Flutter cache",
              path: "\(HOME)/.flutter",
              hint: "Flutter SDK cache",
              cleanup: nil,
              safety: .soft),
    ]),

    // ── Go ─────────────────────────────────────────────────────────────────
    .init(name: "Go", icon: "🐹", targets: [
        .init(label: "module cache",
              path: "\(HOME)/go/pkg/mod",
              hint: "Go module cache (all versions of all dependencies)",
              cleanup: "go clean -modcache",
              safety: .soft),
        .init(label: "build cache",
              path: "\(HOME)/Library/Caches/go-build",
              hint: "Go build cache",
              cleanup: "go clean -cache",
              safety: .safe),
    ]),

    // ── Swift PM ───────────────────────────────────────────────────────────
    .init(name: "Swift PM", icon: "📦", targets: [
        .init(label: "SwiftPM cache",
              path: "\(HOME)/Library/Caches/org.swift.swiftpm",
              hint: "Swift Package Manager cache",
              cleanup: "rm -rf ~/Library/Caches/org.swift.swiftpm",
              safety: .safe),
        .init(label: "SwiftPM checkouts",
              path: "\(HOME)/.swiftpm",
              hint: "SwiftPM dependency checkouts",
              cleanup: nil,
              safety: .soft),
    ]),

    // ── Homebrew ───────────────────────────────────────────────────────────
    .init(name: "Homebrew", icon: "🍺", targets: [
        .init(label: "Homebrew prefix",
              path: "/opt/homebrew",
              hint: "Cellar + all formulae — Homebrew itself",
              cleanup: "brew cleanup --prune=all",
              safety: .manual),
        .init(label: "Homebrew cache",
              path: "\(HOME)/Library/Caches/Homebrew",
              hint: "Downloaded formulae (tarballs, bottles)",
              cleanup: "brew cleanup --prune=all",
              safety: .safe),
    ]),

    // ── Ollama ─────────────────────────────────────────────────────────────
    .init(name: "Ollama", icon: "🦙", targets: [
        .init(label: "models",
              path: "\(HOME)/.ollama/models",
              hint: "Downloaded LLM models (weights + manifests)",
              cleanup: "ollama list",
              safety: .manual,
              subAnalyzer: OllamaModelsAnalyzer()),
    ]),

    // ── Docker ─────────────────────────────────────────────────────────────
    .init(name: "Docker", icon: "🐳", targets: [
        .init(label: "Docker data",
              path: "\(HOME)/Library/Containers/com.docker.docker",
              hint: "Images, containers, volumes — stored in a raw disk image",
              cleanup: "docker system prune -f  # add -a --volumes for full cleanup",
              safety: .manual),
        .init(label: "Docker extensions",
              path: "\(HOME)/Library/Containers/com.docker.docker.helper",
              hint: "Docker Desktop extensions",
              cleanup: nil,
              safety: .soft),
    ]),

    // ── General caches ─────────────────────────────────────────────────────
    .init(name: "App Caches", icon: "📁", targets: [
        .init(label: "~/Library/Caches",
              path: "\(HOME)/Library/Caches",
              hint: "All app caches — macOS recreates as needed",
              cleanup: nil,
              safety: .soft),
        .init(label: "Simulator logs",
              path: "\(HOME)/Library/Logs/CoreSimulator",
              hint: "Xcode simulator logs",
              cleanup: "rm -rf ~/Library/Logs/CoreSimulator",
              safety: .safe),
    ]),
]
